### ISSUE TITLE
UI flashing when a new peer connected

### ISSUE THREAD

**Issue by ok2ju** [interviewr/fugee#17]
When a new peer connected, UI is blinking (a new peer id added to store -> ui connected to this store re-renders). Find out a solution how to get rid of this behaviour.

Steps to reproduce:
1. go to `http://localhost:3333/1` in the fist browser tab;
2. go to the same url in the new tab or window;

Actual result: on the fist tab/window video elements (ui) is blinking;
Expected result: ui remains the same state (not blinking). maybe some visual effect appears to smooth out blinking

**Comment by zarendar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Join to the room](https://trello.com/c/DOzuCNui/14-join-to-the-room)

**Comment by ok2ju** [comment]
Resolved in https://github.com/interviewr/raven-client/pull/35
@BesMarcell check out your branch, maybe you will have conflicts now
