### ISSUE TITLE
Implement tests

### ISSUE THREAD

**Issue by dkryvi** [interviewr/fugee#37]
We need to discuss and make a decision about instruments to test our code.
1. Tool to test code(I prefer [jest](https://jestjs.io/) + [enzyme](https://airbnb.io/enzyme))
2. Tool to show our test coverage([codecov](https://codecov.io)))

What do you think about it?

**Comment by ok2ju** [comment]
Absolutely agree with jest + enzyme. I agree with codecov, but i don't know how to integrate it.

**Comment by dkryvi** [comment]
I have experience with jest+codecov. I can do it

**Comment by ok2ju** [comment]
Resolved in https://github.com/interviewr/raven-client/pull/39

**Comment by ok2ju** [comment]
@DenKrivichanin can we close it? or something to do left?
