### ISSUE TITLE
Add an eslint runtime configuration file

### ISSUE THREAD

**Issue by sidalidev** [interviewr/fugee#55]
In order to make the code more normalized, lets make the code it self yell at people when they have a trailing space or smth 😁

**Comment by ok2ju** [comment]
@sidbentifraouine We use standard (https://standardjs.com/) for linting, you just need to add standard plugin to your favourite code editor (https://standardjs.com/#are-there-text-editor-plugins). When we push code to repository Travis-CI triggers and test, lint stages runs (https://github.com/interviewr/raven-client/blob/develop/package.json#L10)

**Comment by sidalidev** [comment]
@ok2ju Oh okay, awesome !
