### ISSUE TITLE
Upgrade outdated packages

### ISSUE THREAD

**Issue by sidalidev** [interviewr/fugee#56]
<img width="961" alt="screenshot 2018-10-10 at 07 25 27" src="https://user-images.githubusercontent.com/19405039/46714824-b544a600-cc5d-11e8-8889-9115dc1c2fcd.png">

**Comment by ok2ju** [comment]
@sidbentifraouine i have done it in my WIP PR (https://github.com/interviewr/raven-client/pull/52/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)

**Comment by sidalidev** [comment]
@ok2ju didn't see sorry 🙂
